common: &common
  adapter: postgresql
  username: iswhen
  password:

development:
  <<: *common
  database: iswhen_development

test:
  <<: *common
  database: iswhen_test

production:
  <<: *common
  database: iswhen_production

